apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontends
spec:
  secretName: frontends-tls
  issuerRef:
    name: ingress-demo-letsencrypt-cloudflare
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - "*.demo.example.com"
